name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build application
        run: go build -o myapp

      - name: Decode SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ~/.ssh/id_rsa

      - name: Deploy to EC2 instance
        run: |
          ssh ec2-user@${{ secrets.SERVER_IP }} "cd /home/ec2-user/project/go_auth && ./myapp.sh"
